# Email & Communication checkpoint question pools.  [question, CORRECT, wrong, wrong, wrong] (correct first; engine shuffles)

EMAIL = {
    "email-cp1": {
        "track": "email", "title": "Email · Checkpoint 1",
        "covers": ["email-b1", "email-b2", "email-m1", "email-m2"],
        "pool": [
            ["The 'From' line of an email tells you:", "Who sent the email", "Who received it", "The subject", "The date only"],
            ["The 'To' line shows:", "The main person the email is for", "Who sent it", "The attachment", "The signature"],
            ["The 'Cc' line is used for:", "People who get a copy for their information", "The main recipient only", "Hidden recipients", "The subject"],
            ["'Bcc' stands for a copy that is:", "Hidden from the other recipients", "Shown to everyone", "The subject line", "An attachment"],
            ["An email from 'no-reply@notice.com' is most likely:", "An automated message, not a real person", "Your teacher writing personally", "A friend", "A phone call"],
            ["The subject line should:", "Briefly say what the email is about", "Be left blank", "Contain the whole message", "List every recipient"],
            ["To find an old email quickly, you can use the:", "Search bar", "Delete button", "Bold button", "Attachment icon"],
            ["An unread email in the inbox is often shown:", "In bold", "In italic", "Deleted", "As an attachment"],
            ["Opening an email means you:", "Click it to read the full message", "Forward it automatically", "Delete it", "Send a reply instantly"],
            ["Which part of an email is the sender's address?", "The From field", "The subject", "The body", "The signature line only"],
            ["If an email is addressed to you on the 'To' line, you are:", "A main recipient", "Only cc'd", "Bcc'd", "The sender"],
            ["A good subject line for a late-work question is:", "Question about yesterday's homework", "(blank)", "hi", "aaaaaa"],
            ["Searching your inbox for 'field trip' will find:", "Emails containing those words", "Only deleted emails", "Your sent replies only", "Nothing ever"],
            ["The inbox is the folder that holds:", "Emails you have received", "Emails you have sent", "Drafts only", "Deleted emails"],
            ["A person on the Cc line can:", "Read the email as an informational copy", "Never see the email", "Only see the subject", "Edit the email"],
            ["Which is the real human sender among these?", "ms.lee@horizonmiddle.edu", "no-reply@store.com", "notifications@app.com", "auto@system.net"],
            ["The Bcc field is helpful when you want to:", "Copy someone privately without others knowing", "Show everyone the recipient", "Write the subject", "Attach a file"],
            ["Reading the address lines helps you know:", "Who the email is for and who else can see it", "The font size", "The file size", "The weather"],
            ["If you can't find an email, a smart step is to:", "Search using a keyword from it", "Delete your inbox", "Turn off the computer", "Bold the subject"],
            ["The main recipient of an email belongs on which line?", "To", "Cc", "Bcc", "Subject"],
            ["A blank subject line is a problem because:", "The reader can't tell what the email is about", "It sends faster", "It adds an attachment", "It hides the sender"],
            ["Which field is for extra people who just need a copy?", "Cc", "To", "Subject", "Body"],
            ["An email's 'body' is:", "The main message text", "The sender's address", "The subject", "The date"],
            ["To tell a class newsletter from a personal email, check the:", "Sender (From) and the tone", "Font", "Screen brightness", "Battery level"],
        ],
    },
    "email-cp2": {
        "track": "email", "title": "Email · Checkpoint 2",
        "covers": ["email-m3", "email-m4", "email-m5", "email-m6"],
        "pool": [
            ["When you reply to an email, the subject usually starts with:", "Re:", "Fwd:", "New:", "Cc:"],
            ["'Reply' sends your response to:", "The original sender", "Everyone on the email", "Nobody", "A hidden list"],
            ["'Reply All' sends your response to:", "The sender AND everyone else on the email", "Only you", "Only the sender", "No one"],
            ["When should you use Reply All?", "When everyone truly needs your response", "For a private note to one person", "Never", "To hide your reply"],
            ["Forwarding an email means:", "Sending it on to a new person", "Deleting it", "Replying to the sender", "Changing the sender"],
            ["A forwarded email's subject usually starts with:", "Fwd:", "Re:", "Cc:", "Bcc:"],
            ["A professional email should begin with a:", "Greeting (like 'Dear Ms. Lee,')", "The word 'yo'", "No opening at all", "The attachment"],
            ["A professional email should end with a:", "Sign-off and your name (like 'Thanks, Jordan')", "Blank line", "A random symbol", "The subject"],
            ["Composing a NEW email means you:", "Start a fresh message from scratch", "Reply to an old one", "Forward one", "Delete one"],
            ["When you compose, the subject line should be:", "Short and clear about the topic", "Left blank", "The entire message", "Just 'hi'"],
            ["If only the sender needs your answer, you should use:", "Reply", "Reply All", "Forward", "Bcc everyone"],
            ["Sending 'Reply All' to a huge group for a one-person answer is:", "Poor etiquette (spams everyone)", "Always best", "Required", "Impossible"],
            ["Before forwarding, it's polite to:", "Add a short note explaining why", "Erase the subject", "Remove the To line", "Send it blank"],
            ["A greeting in an email is like:", "Saying hello at the start", "The signature", "The attachment", "The subject"],
            ["Which is a good sign-off?", "Sincerely, Jordan", "(nothing)", "Re:", "no-reply"],
            ["When you Reply, the original message is usually:", "Quoted below your response", "Deleted", "Sent to Bcc", "Turned into a chart"],
            ["Composing to your teacher, a good greeting is:", "Dear Ms. Lee,", "hey u", "yo teach", "(blank)"],
            ["Reply All keeps everyone 'in the loop,' meaning:", "All original recipients see your reply", "Only you see it", "The email is deleted", "The subject changes to Fwd:"],
            ["A complete email should have a greeting, a message, and a:", "Sign-off", "Chart", "Formula", "Transition"],
            ["Forwarding is best when:", "Someone new needs to see the message", "You want to answer the sender", "You want to delete it", "You need a copy for yourself only"],
            ["If you forward an email, the new recipient goes in the:", "To line", "From line", "Subject", "Signature"],
            ["A message with only 'ok' and no greeting or sign-off is:", "Not following email protocol", "Perfectly professional", "A forward", "A subject line"],
            ["Reply vs Reply All: choosing Reply protects others from:", "Getting unnecessary messages", "Reading the subject", "Seeing the sender", "The greeting"],
            ["The safest choice when unsure between Reply and Reply All is:", "Reply (to just the sender), unless all need it", "Always Reply All", "Forward to strangers", "Bcc the class"],
        ],
    },
    "email-cp3": {
        "track": "email", "title": "Email · Checkpoint 3",
        "covers": ["email-m7", "email-m8", "email-m9", "email-m10", "email-m11", "email-m12"],
        "pool": [
            ["Put the MAIN recipient of an email in the:", "To field", "Cc field", "Bcc field", "Subject field"],
            ["People who only need a copy for awareness go in the:", "Cc field", "To field", "Subject", "Body"],
            ["To copy someone WITHOUT others seeing their address, use:", "Bcc", "Cc", "To", "Reply All"],
            ["An 'attachment' is:", "A file sent along with the email", "The greeting", "The subject", "The signature"],
            ["When you attach a file, it's polite to:", "Mention the attachment in your message", "Say nothing about it", "Delete the subject", "Remove the greeting"],
            ["A common attachment type for a document is:", "PDF", "MP3 only", "A phone number", "A cell reference"],
            ["Bolding a key word in an email helps by:", "Drawing attention to important info", "Deleting the word", "Hiding the word", "Changing the sender"],
            ["A bulleted list in an email is good for:", "Listing several items clearly", "One short sentence", "The subject line", "The From field"],
            ["An email 'signature' usually includes your:", "Name (and maybe role/contact)", "Password", "The recipient's address", "The attachment"],
            ["Good email etiquette means writing in a tone that is:", "Polite and professional", "Rude", "All capital letters", "Full of slang"],
            ["WRITING AN EMAIL IN ALL CAPS usually reads as:", "Shouting / rude", "Very polite", "Professional", "A greeting"],
            ["A 'formal' email register is right for:", "A teacher, principal, or employer", "Your best friend joking", "A text to a sibling", "A meme"],
            ["An 'informal' tone is okay for:", "A close friend or family member", "A job application", "The principal", "A formal complaint"],
            ["Which greeting is most formal?", "Dear Dr. Nguyen,", "hey", "yo", "sup"],
            ["Proper grammar and spelling in an email make you look:", "Careful and professional", "Careless", "Funny", "Anonymous"],
            ["Before sending an important email, you should:", "Proofread it for tone and errors", "Add typos", "Remove the greeting", "Delete the subject"],
            ["Which belongs in a professional sign-off?", "Thank you, Jordan Rivera", "no-reply", "Re: Re: Re:", "asdf"],
            ["If you forget the attachment you mentioned, the reader will be:", "Confused (there's nothing attached)", "Happy", "Unaffected", "Automatically sent it"],
            ["Choosing the right recipient field (To/Cc/Bcc) shows you:", "Understand who the message is really for", "Like bright colors", "Want to delete it", "Prefer bold text"],
            ["A semi-formal email might be sent to:", "A coach or a familiar teacher", "A stranger applying for a job", "A judge", "The President"],
            ["The capstone 'manage your morning inbox' asked you to:", "Locate, reply, forward, and compose appropriately", "Delete everything", "Ignore all emails", "Only read the subjects"],
            ["Emailing a mentor for the first time, the best tone is:", "Respectful and professional", "Super casual with slang", "Demanding", "All emojis"],
            ["Attaching a file is done with which button?", "The paperclip / Attach button", "Bold", "The subject line", "Reply All"],
            ["Formatting (bold, bullets) in an email should be used to:", "Make the message clearer, not decorate it", "Fill space", "Hide the point", "Replace the greeting"],
        ],
    },
}
