# Spreadsheets checkpoint question pools.  [question, CORRECT, wrong, wrong, wrong] (correct first; engine shuffles)

SHEETS = {
    "sheets-cp1": {
        "track": "sheets", "title": "Spreadsheets · Checkpoint 1",
        "covers": ["sheets-m1", "sheets-m2", "sheets-m3", "sheets-m4"],
        "pool": [
            ["A single box in a spreadsheet is called a:", "Cell", "Row only", "Tab", "Ribbon"],
            ["The label 'B3' refers to:", "Column B, row 3", "Row B, column 3", "The 3rd sheet", "Cell number 23"],
            ["Columns in a spreadsheet are labeled with:", "Letters", "Numbers", "Symbols", "Colors"],
            ["Rows in a spreadsheet are labeled with:", "Numbers", "Letters", "Symbols", "Dates"],
            ["Every formula in a spreadsheet begins with which symbol?", "= (equals sign)", "+ (plus)", "# (hash)", "@ (at)"],
            ["What does =SUM(A1:A5) do?", "Adds the values in cells A1 through A5", "Counts how many cells there are", "Finds the average", "Sorts the column"],
            ["The colon in A1:A5 means:", "A range from A1 to A5", "Divide A1 by A5", "Only A1 and A5", "Subtract"],
            ["What does =AVERAGE(B1:B4) calculate?", "The mean of B1 through B4", "The largest value", "The total", "The count"],
            ["To average numbers, AVERAGE adds them and then:", "Divides by how many there are", "Multiplies them", "Sorts them", "Rounds to zero"],
            ["What does =COUNT(A1:A10) return?", "How many cells in the range contain numbers", "The sum of the range", "The average", "The biggest number"],
            ["Which is a correctly written formula?", "=SUM(A1:A3)", "SUM A1 A3", "+SUM(A1-A3)", "sum=A1:A3"],
            ["If A1=2, A2=4, A3=6, then =SUM(A1:A3) equals:", "12", "6", "4", "3"],
            ["If A1=2, A2=4, A3=6, then =AVERAGE(A1:A3) equals:", "4", "12", "6", "2"],
            ["The intersection of a row and a column is a:", "Cell", "Chart", "Formula", "Sheet tab"],
            ["Which cell reference is column D, row 10?", "D10", "10D", "D-10", "R10D"],
            ["A 'range' means:", "A group of cells", "One single cell only", "A whole file", "A font"],
            ["=COUNT is different from =SUM because COUNT:", "Counts how many numbers there are, not their total", "Adds them up", "Averages them", "Sorts them"],
            ["Where do you type a formula so it calculates?", "In a cell (or the formula bar)", "In the title bar", "In the file name", "On the chart"],
            ["If you change a number that a =SUM uses, the sum will:", "Update automatically", "Stay the same", "Delete itself", "Turn red"],
            ["The formula bar shows:", "The formula inside the selected cell", "The page number", "The font", "The chart title"],
            ["Which range covers the first four cells of column C?", "C1:C4", "C1-C4 only C1 and C4", "1C:4C", "C4:C1 backwards only"],
            ["=AVERAGE of 10, 20, 30 is:", "20", "60", "30", "10"],
            ["A spreadsheet is best for working with:", "Numbers and data in a grid", "Long essays", "Slideshows", "Photos only"],
            ["If a formula is typed WITHOUT the = sign, the cell will:", "Show it as plain text, not calculate", "Still calculate", "Delete the row", "Make a chart"],
        ],
    },
    "sheets-cp2": {
        "track": "sheets", "title": "Spreadsheets · Checkpoint 2",
        "covers": ["sheets-m5", "sheets-m6", "sheets-m7", "sheets-m8"],
        "pool": [
            ["What does =MAX(A1:A10) return?", "The largest value in the range", "The smallest value", "The total", "The average"],
            ["What does =MIN(A1:A10) return?", "The smallest value in the range", "The largest value", "The count", "The sum"],
            ["If the range holds 5, 9, 2, 7, then =MAX returns:", "9", "2", "5", "7"],
            ["If the range holds 5, 9, 2, 7, then =MIN returns:", "2", "9", "7", "5"],
            ["A 'summary row' often combines which functions?", "SUM, AVERAGE, MAX, and MIN", "Only bold and italic", "Charts and images", "Fonts and colors"],
            ["Sorting a column of names A→Z is called:", "Ascending order", "Descending order", "Random order", "Reverse order"],
            ["Sorting numbers from largest to smallest is:", "Descending order", "Ascending order", "Alphabetical", "Random"],
            ["A bar chart is best for:", "Comparing amounts across categories", "Showing parts of a whole", "Writing paragraphs", "Storing formulas"],
            ["Which menu is used to insert a chart?", "Insert", "Home", "Data only", "View"],
            ["When you sort data, you should usually select:", "The whole table so rows stay together", "Only one number", "The chart", "The title bar"],
            ["=MAX and =MIN are useful for finding:", "The highest and lowest values quickly", "The total", "The average only", "The font size"],
            ["A bar chart's bars represent:", "Values for each category", "The formula bar", "Cell borders", "Page numbers"],
            ["Before making a bar chart, you first:", "Select the data to chart", "Delete the data", "Change the font", "Save as PDF"],
            ["Sorting a list of test scores highest-first uses:", "Descending order", "Ascending order", "Alphabetical A-Z", "No sort"],
            ["A summary row is usually placed:", "At the bottom of the data", "In the title", "In a chart", "In the header only"],
            ["If you sort ONLY one column and not the others, your data can become:", "Mismatched / scrambled", "More accurate", "A chart", "Bold"],
            ["Which formula finds the top score in B2:B20?", "=MAX(B2:B20)", "=MIN(B2:B20)", "=SUM(B2:B20)", "=COUNT(B2:B20)"],
            ["Which formula finds the lowest price in C2:C30?", "=MIN(C2:C30)", "=MAX(C2:C30)", "=AVERAGE(C2:C30)", "=SUM(C2:C30)"],
            ["A chart helps a reader:", "Understand data visually at a glance", "Add more formulas", "Change the font", "Sort automatically"],
            ["The chart title should:", "Describe what the chart shows", "Be left blank", "List every formula", "Show the file size"],
            ["Ascending order for the word list (apple, mango, banana) would start with:", "apple", "mango", "banana", "no change"],
            ["A summary row that uses =AVERAGE tells you the:", "Typical (mean) value", "Largest value", "Count", "Smallest value"],
            ["To compare monthly sales for Jan–Jun, a good chart is a:", "Bar chart", "A single cell", "A formula bar", "A header"],
            ["If MAX equals MIN for a range, that means:", "All the values are the same", "The range is empty", "There is an error", "The chart is broken"],
        ],
    },
    "sheets-cp3": {
        "track": "sheets", "title": "Spreadsheets · Checkpoint 3",
        "covers": ["sheets-m9", "sheets-m10", "sheets-m11"],
        "pool": [
            ["A pie chart is best for showing:", "Parts of a whole (percentages)", "Change over many years", "A single number", "Text paragraphs"],
            ["Each slice of a pie chart represents:", "A portion of the total", "A formula", "A row label", "A page number"],
            ["If a pie chart slice is half the circle, it represents about:", "50%", "10%", "90%", "5%"],
            ["A workbook can contain multiple:", "Worksheets (sheet tabs)", "Printers", "Fonts only", "Web pages"],
            ["Sheet tabs are found:", "At the bottom of the spreadsheet", "In the title bar", "Inside a cell", "On the ribbon"],
            ["To rename a worksheet tab, you usually:", "Double-click the tab and type a new name", "Delete the file", "Change the font", "Make a chart"],
            ["Using separate worksheets helps you:", "Organize different data on different tabs", "Add more colors", "Print faster only", "Remove formulas"],
            ["A pie chart would work well to show:", "How a budget is split among categories", "Daily temperature over a month", "A list of names", "One test score"],
            ["Which is NOT a good use of a pie chart?", "Tracking a value across 20 years", "Showing budget percentages", "Showing survey answer shares", "Showing how a pizza is divided"],
            ["The capstone gradebook task asked you to use formulas and then:", "Export/organize a finished gradebook", "Delete all data", "Turn off formulas", "Remove the tabs"],
            ["Adding a new worksheet is done by clicking:", "The + (plus) near the sheet tabs", "The Bold button", "File → Print", "The formula bar"],
            ["A pie chart's slices should add up to about:", "100%", "50%", "10%", "0%"],
            ["Two worksheets in the same file can hold:", "Related but separate data (e.g., Term 1 and Term 2)", "Only identical data", "No data", "Only charts"],
            ["Before making a pie chart, you select:", "The categories and their values", "Just the title", "A single empty cell", "The whole screen"],
            ["Renaming tabs to 'Sales' and 'Costs' makes a workbook:", "Easier to navigate and understand", "Slower", "Bold", "Larger in font"],
            ["A gradebook spreadsheet might use =AVERAGE to compute:", "Each student's average grade", "The font color", "The number of tabs", "The chart title"],
            ["If a pie chart has only ONE slice, it means:", "One category is 100% of the total", "There is no data", "The chart is a bar chart", "An error occurred"],
            ["Worksheet tabs let you switch between:", "Different pages of data in one file", "Different fonts", "Different printers", "Different apps"],
            ["A bar chart vs a pie chart: use a pie chart when you care about:", "Share of the whole", "Exact change over time", "Sorting", "Word count"],
            ["To highlight the top student in a gradebook, you might find the:", "MAX of the averages", "MIN of the averages", "COUNT of tabs", "font size"],
            ["The color of each pie slice should:", "Be different so slices are easy to tell apart", "All be identical", "Match the background", "Be invisible"],
            ["Multiple worksheets are stored inside one:", "Workbook (file)", "Cell", "Chart", "Row"],
            ["A gradebook's summary row might show class:", "Average, highest, and lowest scores", "Fonts", "Page numbers", "Tab colors"],
            ["Which chart shows how 100 survey students split among 4 answers best?", "Pie chart", "A single cell", "A formula bar", "A header row"],
        ],
    },
}
