# Word Processing checkpoint question pools.
# Format per question: [question, CORRECT_answer, wrong, wrong, wrong]  (correct is always first; engine shuffles per student)

DOCS = {
    "docs-cp1": {
        "track": "docs", "title": "Word Processing · Checkpoint 1",
        "covers": ["docs-m1", "docs-m2", "docs-m3", "docs-m4"],
        "pool": [
            ["What is the strip of tabs and buttons across the top of a word processor called?", "The Ribbon", "The Taskbar", "The Status bar", "The Scroll bar"],
            ["Which Ribbon tab holds Bold, Italic, and font options?", "Home", "Insert", "View", "References"],
            ["What does the Bold button do to selected text?", "Makes it thicker and darker", "Makes it slanted", "Adds a line under it", "Changes its color"],
            ["Which keyboard shortcut usually applies Bold?", "Ctrl + B", "Ctrl + I", "Ctrl + U", "Ctrl + P"],
            ["The Italic button makes text look how?", "Slanted", "Underlined", "Larger", "Colored"],
            ["What does the Underline button add to text?", "A line beneath it", "A box around it", "A shadow", "A highlight"],
            ["The 'font family' setting controls what?", "The typeface (like Arial or Times)", "How dark the text is", "The page margins", "The line spacing"],
            ["Font size is measured in what unit?", "Points", "Inches", "Pixels only", "Centimeters"],
            ["Which font size would look the largest?", "48 pt", "12 pt", "18 pt", "24 pt"],
            ["To change only a few words to bold, you should first do what?", "Select (highlight) those words", "Save the document", "Close the ribbon", "Print the page"],
            ["Which of these is a typeface (font family)?", "Calibri", "Bold", "Italic", "12 point"],
            ["What does the Text Color button change?", "The color of the letters", "The background of the page", "The font size", "The page number"],
            ["The Text Color button usually shows which icon?", "A letter 'A' with a colored bar under it", "A paintbrush", "A pair of scissors", "A magnifying glass"],
            ["Bold, Italic, and Underline are found in which Ribbon group on the Home tab?", "Font group", "Paragraph group", "Clipboard group", "Editing group"],
            ["Which shortcut usually applies Italic?", "Ctrl + I", "Ctrl + B", "Ctrl + U", "Ctrl + S"],
            ["If text is too small to read on screen, what should you increase?", "The font size", "The margins", "The word count", "The zoom of the printer"],
            ["You can apply Bold AND Italic to the same text at the same time.", "True", "False — only one at a time", "Only in headings", "Only in tables"],
            ["Where do you look to see which font a selected word is using?", "The Font box on the Home tab", "The status bar", "The File menu", "The ruler"],
            ["What is the best reason to change a font family?", "To match the tone or style of the document", "To make the file smaller", "To add page numbers", "To check spelling"],
            ["Underlining a word is most similar in purpose to which other emphasis tool?", "Bold — both add emphasis", "The zoom slider", "The save button", "The margin setting"],
            ["Which is NOT a font style button in the Font group?", "Print", "Bold", "Italic", "Underline"],
            ["To make a title stand out at the top of a report, a good choice is to make it:", "Larger and bold", "Smaller and grey", "Italic and tiny", "Underlined and 8 pt"],
            ["After selecting text, clicking the Bold button a second time will:", "Turn Bold off again", "Delete the text", "Make it italic", "Change the color"],
            ["The point size '11' compared to '11.5' is:", "Slightly smaller", "Much larger", "The same", "A different font"],
        ],
    },
    "docs-cp2": {
        "track": "docs", "title": "Word Processing · Checkpoint 2",
        "covers": ["docs-m5", "docs-m6", "docs-m7", "docs-m8"],
        "pool": [
            ["Which alignment lines text up on the LEFT edge only?", "Left align", "Center align", "Right align", "Justify"],
            ["Which alignment centers text between the margins?", "Center align", "Left align", "Justify", "Right align"],
            ["'Justify' alignment does what to a paragraph?", "Lines up text on BOTH left and right edges", "Centers every line", "Puts text on the right only", "Makes text bold"],
            ["Right alignment is often used for what?", "Dates or numbers at the top of a letter", "The main body of an essay", "Page titles", "Bullet lists"],
            ["What does 'line spacing' control?", "The vertical space between lines of text", "The space between letters", "The font color", "The margin width"],
            ["Double spacing (2.0) compared to single spacing (1.0) means:", "More space between lines", "Less space between lines", "Bigger letters", "A new font"],
            ["A bulleted list is best for:", "Items with no particular order", "Steps that must happen in order", "A single sentence", "A page title"],
            ["A numbered list is best for:", "Steps that happen in a specific order", "Random ideas", "One word", "A signature"],
            ["Which symbol usually marks a bulleted list item?", "A dot (•)", "A number", "A dollar sign", "A question mark"],
            ["The Insert menu can add which of these?", "Symbols and special characters", "A new font family", "Line spacing", "Bold text"],
            ["A hyperlink in a document lets a reader do what?", "Click to jump to a web page or place", "Change the font", "Print faster", "Add a bullet"],
            ["Which is an example of a special symbol you might Insert?", "Ω (omega)", "The letter A", "A space", "A period"],
            ["Alignment and line spacing buttons live in which Ribbon group?", "Paragraph group", "Font group", "Insert group", "Clipboard group"],
            ["To turn a set of sentences into a bulleted list, you first:", "Select the lines, then click the bullet button", "Delete them", "Bold them", "Change the font"],
            ["Which alignment makes both side edges of a paragraph straight, like a newspaper column?", "Justify", "Center", "Left", "Right"],
            ["Increasing line spacing makes a document:", "Easier to read and mark up", "Shorter", "Bold", "Centered"],
            ["A good use of a hyperlink is to:", "Link to a source you used", "Underline a title", "Add a page number", "Change spacing"],
            ["When inserting a hyperlink, the 'display text' is:", "The words the reader sees and clicks", "The web address only", "The font size", "The bullet symbol"],
            ["Center alignment is a common choice for:", "A title or heading", "A long paragraph of body text", "A footnote", "A date line"],
            ["Which list type would you use for a recipe's steps?", "Numbered list", "Bulleted list", "No list", "A table of contents"],
            ["1.5 line spacing is:", "Between single and double spacing", "Larger than double", "The same as single", "A font size"],
            ["To type a character not on your keyboard (like é or ©), you use:", "Insert → Symbol", "Bold", "Justify", "Find & Replace"],
            ["Bullets and numbering are examples of:", "Lists", "Fonts", "Margins", "Themes"],
            ["Left alignment is the default (normal) alignment for most:", "Body paragraphs", "Page numbers", "Titles", "Dates"],
        ],
    },
    "docs-cp3": {
        "track": "docs", "title": "Word Processing · Checkpoint 3",
        "covers": ["docs-m9", "docs-m10", "docs-m11", "docs-m12"],
        "pool": [
            ["What does the Find & Replace tool do?", "Locates text and can swap it for new text", "Changes the font", "Adds a table", "Prints the file"],
            ["Find & Replace is useful when you want to:", "Change every 'color' to 'colour' at once", "Bold one word", "Add a picture", "Center a title"],
            ["A table in a document is made of:", "Rows and columns of cells", "Only bullet points", "A single line", "Page numbers"],
            ["The box where a row and column meet in a table is called a:", "Cell", "Tab", "Margin", "Bullet"],
            ["To insert a 3x4 table means:", "3 columns and 4 rows (or 3 rows, 4 columns)", "3 pages", "3 fonts", "4 symbols"],
            ["A header appears where on the page?", "At the top margin of every page", "At the bottom", "In the middle", "Only page 1's body"],
            ["A footer appears where on the page?", "At the bottom margin of every page", "At the very top", "In the center", "In a table"],
            ["Page numbers are usually placed in the:", "Header or footer", "Middle of the body", "First cell of a table", "Font box"],
            ["Which menu is used to add a table?", "Insert", "Home", "View", "References"],
            ["Exporting a document 'to PDF' is helpful because a PDF:", "Looks the same on any device and can't be easily edited", "Is always smaller than the words", "Adds spelling errors", "Removes all formatting"],
            ["In many programs, exporting to PDF is done from which menu?", "File → Download/Export as PDF", "Insert → Symbol", "Home → Bold", "View → Zoom"],
            ["Find & Replace can replace text 'All' at once, which means:", "Every match is changed in one click", "Only the first match", "Nothing is changed", "The file is deleted"],
            ["A good reason to use a table is to:", "Organize data neatly in rows and columns", "Add color to text", "Insert a hyperlink", "Change spacing"],
            ["Headers and footers are added from which menu?", "Insert", "Home", "Edit", "Format"],
            ["If you want your name on every page automatically, put it in the:", "Header or footer", "First paragraph only", "A bullet list", "The title bar"],
            ["When you Replace 'teh' with 'the', Find & Replace fixes:", "A common typo everywhere it appears", "The font", "The margins", "The page size"],
            ["To add a new row to a table, you usually:", "Use the table tools / right-click → Insert row", "Change the font", "Press Ctrl+B", "Open File menu"],
            ["A PDF is a good format to submit an assignment because:", "The teacher sees your exact layout", "It can be edited by anyone", "It removes your name", "It changes fonts randomly"],
            ["Which of these belongs in a footer?", "A page number", "The document's main heading", "A body paragraph", "A chart"],
            ["Find & Replace is found on which tab/menu in most editors?", "Home/Edit (Editing group)", "Insert", "Design", "Layout"],
            ["The capstone task asked you to format a document and then:", "Export it as a PDF", "Delete it", "Email it to nobody", "Change the language"],
            ["A table's columns run in which direction?", "Up and down (vertical)", "Left and right (horizontal)", "Diagonally", "In a circle"],
            ["A table's rows run in which direction?", "Left and right (horizontal)", "Up and down (vertical)", "Diagonally", "Randomly"],
            ["Before exporting to PDF, it is smart to:", "Proofread and check the formatting", "Delete the header", "Remove all fonts", "Turn off the screen"],
        ],
    },
}
