# Presentations checkpoint question pools.  [question, CORRECT, wrong, wrong, wrong] (correct first; engine shuffles)

SLIDES = {
    "slides-cp1": {
        "track": "slides", "title": "Presentations · Checkpoint 1",
        "covers": ["slides-m1", "slides-m2", "slides-m3", "slides-m4"],
        "pool": [
            ["The first slide of a presentation is usually the:", "Title slide", "Chart slide", "Closing slide", "Notes page"],
            ["A title slide should contain the:", "Presentation title (and maybe your name)", "Whole essay", "A spreadsheet", "Speaker notes only"],
            ["A 'deck' in presentation software means:", "The whole set of slides", "One paragraph", "A single image", "A chart"],
            ["Each slide in a deck should have a:", "Clear title", "A different font on every word", "No text at all", "A full essay"],
            ["Body text on a slide is usually shown as:", "Short bullet points", "Long paragraphs", "One giant sentence", "A formula"],
            ["The 5×5 rule suggests about how many bullets per slide?", "About 5 (with ~5 words each)", "25 bullets", "1 word only", "50 words"],
            ["The 5×5 rule helps a slide by keeping text:", "Short and readable", "Long and detailed", "Colorful", "Bold"],
            ["Why keep slides from having too much text?", "The audience reads instead of listening", "It saves paper", "It changes the font", "It adds animations"],
            ["A bullet point should be:", "A short phrase, not a full paragraph", "A whole page of text", "An image only", "A chart"],
            ["Adding a new slide is done from which area?", "The New Slide / Insert control", "The formula bar", "Find & Replace", "The footer"],
            ["Good bullet points are:", "Concise and to the point", "Complete essays", "Random words", "Only numbers"],
            ["The title slide's job is to:", "Introduce the topic clearly", "List every detail", "Show the conclusion", "Hold the speaker notes"],
            ["Which follows the 5×5 rule best?", "5 bullets, ~5 words each", "One 40-word sentence", "10 dense paragraphs", "No title, all text"],
            ["Bulleted content is easier to follow than paragraphs because it is:", "Broken into small, scannable pieces", "Longer", "In color", "Animated"],
            ["A presentation is mainly a tool to:", "Support a spoken talk with visuals", "Replace all speaking", "Store formulas", "Print letters"],
            ["Each slide's title helps the audience know:", "What that slide is about", "The file size", "Your font choice", "The page number of a book"],
            ["Too many words on a slide usually makes it:", "Hard to read from the back of a room", "Easier to present", "More professional", "Load faster"],
            ["When building a deck, every slide should generally have:", "A title and focused content", "No title", "A spreadsheet", "The same photo"],
            ["A bullet list on a slide should use:", "Parallel, short phrases", "Full paragraphs", "One long run-on line", "Only emojis"],
            ["The main heading you type first goes on the:", "Title slide", "Last slide", "Notes page", "Handout only"],
            ["If a slide has 8 long bullet points, a good fix is to:", "Split it into two slides with fewer bullets", "Add more bullets", "Make the font tiny", "Delete the title"],
            ["The audience should mostly be:", "Listening to you, using slides as support", "Reading everything on the slide", "Ignoring you", "Taking the quiz"],
            ["A clear, short slide title is an example of good:", "Design and communication", "Spreadsheet math", "Email etiquette", "Font color theory"],
            ["Which is the BEST title-slide title for a talk on recycling?", "Recycling at Our School", "asdf123", "Slide 1", "Untitled"],
        ],
    },
    "slides-cp2": {
        "track": "slides", "title": "Presentations · Checkpoint 2",
        "covers": ["slides-m5", "slides-m6", "slides-m7", "slides-m8"],
        "pool": [
            ["A slide 'layout' determines:", "Where titles, text, and images are placed", "The font color only", "The animation speed", "The file name"],
            ["A 'Title and Content' layout is good for:", "A slide with a heading and bullet points", "Only a picture", "A blank slide", "A spreadsheet"],
            ["A 'theme' in a presentation controls the:", "Overall colors, fonts, and look", "Number of slides", "Spelling", "Speaker notes"],
            ["Applying a theme keeps a deck looking:", "Consistent across all slides", "Different on every slide", "Black and white only", "Text-free"],
            ["Why insert an image on a slide?", "To illustrate or support the point", "To make the file smaller", "To add formulas", "To remove the title"],
            ["Images on a slide should be:", "Clear and relevant to the topic", "Blurry and random", "Covering all the text", "Tiny in a corner always"],
            ["A chart on a slide is useful to:", "Show data visually to the audience", "Replace the title", "Add speaker notes", "Change the theme"],
            ["Choosing the right layout BEFORE adding content helps you:", "Place things neatly and save time", "Slow down the computer", "Delete slides", "Change fonts randomly"],
            ["A theme is best chosen so it:", "Matches the topic and stays readable", "Uses the brightest possible colors", "Hides the text", "Changes each slide"],
            ["Which layout would you pick for just a big photo and a caption?", "Picture with caption layout", "Blank formula layout", "Two-column essay", "Title-only spreadsheet"],
            ["When you add an image, you should also:", "Resize it so it fits without covering text", "Stretch it over everything", "Delete the slide title", "Turn it upside down"],
            ["A bar or pie chart on a slide comes from:", "Insert → Chart", "The footer", "Find & Replace", "Speaker notes"],
            ["Consistent themes make a presentation look:", "Professional and polished", "Messy", "Longer", "Slower"],
            ["A good reason to change a slide's layout is:", "The content changed (e.g., you added an image)", "To confuse the audience", "To remove the title", "To add typos"],
            ["Images that are relevant help the audience:", "Understand and remember the point", "Get distracted", "Read less of your talk", "Skip the slide"],
            ["If a theme's text color is hard to read on its background, you should:", "Choose a theme/colors with better contrast", "Keep it anyway", "Make the font smaller", "Remove all text"],
            ["A chart title on a slide should:", "Say what the chart shows", "Be blank", "List the theme name", "Be the file size"],
            ["Layouts, themes, and images are all part of good slide:", "Design", "Spelling", "Math", "Emailing"],
            ["Too many different themes in one deck will make it look:", "Disorganized", "Professional", "Shorter", "Faster"],
            ["Before inserting a chart, your data should be:", "Ready/organized so the chart is accurate", "Deleted", "In a different app only", "Hidden"],
            ["The safest image choice for a school project is one that is:", "Relevant and appropriate", "Off-topic", "Covering the title", "Very blurry"],
            ["A 'Two Content' layout lets you place:", "Two side-by-side content areas", "Only one word", "A single giant image", "Speaker notes"],
            ["Themes save time because they style:", "All slides at once", "Only slide 1", "Just the images", "Only the notes"],
            ["A chart is better than a table of numbers on a slide when you want to:", "Show a trend or comparison quickly", "List exact values only", "Save the file", "Add animation"],
        ],
    },
    "slides-cp3": {
        "track": "slides", "title": "Presentations · Checkpoint 3",
        "covers": ["slides-m9", "slides-m10", "slides-m11", "slides-m12"],
        "pool": [
            ["An 'animation' in a presentation controls how:", "An element appears or moves ON a slide", "You switch between slides", "The file saves", "The font is chosen"],
            ["A 'transition' controls how:", "You move from one slide to the NEXT", "Text appears within a slide", "A chart is made", "The theme is set"],
            ["The difference between animation and transition is:", "Animation = within a slide; transition = between slides", "They are the same", "Both are fonts", "Both are charts"],
            ["Too many flashy animations can:", "Distract the audience from your message", "Improve understanding always", "Save time", "Fix typos"],
            ["Speaker notes are:", "Private notes to help YOU present", "Shown big to the audience", "The slide title", "A chart"],
            ["Who normally sees the speaker notes?", "The presenter (not the audience)", "Everyone on the big screen", "Only the teacher's email", "Nobody ever"],
            ["A good use of a subtle transition is to:", "Signal moving to a new idea", "Hide the content", "Replace speaking", "Change the theme"],
            ["Speaker notes help a presenter:", "Remember what to say", "Add more bullets to the slide", "Change the font", "Sort data"],
            ["The capstone asked you to build a deck and then:", "Present it (and export/share it)", "Delete it", "Turn off the title", "Remove all slides"],
            ["Animations should be used:", "Sparingly and with purpose", "On every single word", "Never on any slide", "Only to hide text"],
            ["If every slide has a loud spinning transition, the talk feels:", "Distracting and less professional", "Clear", "Shorter", "More trustworthy"],
            ["Speaker notes appear in the editing view:", "Below or beside the slide", "As a big banner", "Inside the chart", "In the file name"],
            ["A presenter who reads directly off the slides should instead:", "Use speaker notes and talk to the audience", "Add more text to slides", "Remove the title", "Use more animations"],
            ["A transition applied 'to all slides' means:", "Every slide change uses that effect", "Only slide 1 changes", "Text animates", "The theme changes"],
            ["The best animations:", "Reveal points one at a time to guide attention", "Cover the whole slide", "Spin constantly", "Play random sounds"],
            ["Before presenting, you should:", "Rehearse using your speaker notes", "Delete your notes", "Add 20 animations", "Change every theme"],
            ["Speaker notes are a good place to write:", "Key facts and reminders for each slide", "The slide's visible title", "The chart data", "The file size"],
            ["A subtle 'fade' transition is usually:", "Professional and easy on the eyes", "Distracting", "Impossible", "A font"],
            ["Animations and transitions are both about:", "Delivering the presentation smoothly", "Doing spreadsheet math", "Email etiquette", "Saving as PDF only"],
            ["When you present the capstone deck, the slides should:", "Support what you say, not replace it", "Contain your entire script", "Be blank", "Only show animations"],
            ["Using speaker notes well means the audience sees:", "Clean slides while you stay on track", "All your notes", "A messy slide", "The file menu"],
            ["A transition that is too slow can:", "Waste time between slides", "Speed up the talk", "Fix spelling", "Add a chart"],
            ["The purpose of rehearsing is to:", "Make your delivery smooth and confident", "Add more slides", "Change fonts", "Delete notes"],
            ["Which combo is best for a school presentation?", "Clean slides, subtle transitions, helpful speaker notes", "Heavy animations on every word", "No titles and tiny text", "One slide with an essay"],
        ],
    },
}
